### PR TITLE
Add vignette for how to classify the proportion of code in a document (and across multiple documents)

### PR DESCRIPTION
**Pull request by jrosen48**
Per #5, this is a vignette for how to classify the proportion of code in a document (and across multiple documents). Please let us know what to change! Thank you!

### CODE REVIEW

**Comment by jrosen48** [comment]
Just wanted to touch base on this - and whether there are any changes you'd like us to make!

**Comment by jrosen48** [comment]
Hi again, just thought to message about this---would it be better to post this as a blog post on one or both of our blogs? Thanks!

**Comment by LucyMcGowan** [comment]
Oh goodness sorry I’ve missed this! I’ll look over ASAP!

**Comment by jrosen48** [comment]
No prob! Thanks so much!

**Comment by LucyMcGowan** [comment]
Looks awesome, thank you!

**Comment by LucyMcGowan** [comment]
@jrosen48 I've added you as a contributor: https://github.com/LucyMcGowan/tidycode/blob/3a737482c0474791f169f20fd057d4638b6e3eb2/DESCRIPTION#L8 Feel free to add details in a PR - thanks again!

**Pull request merged**
